ActionMailer::Base.delivery_method = :smtp
ActionMailer::Base.smtp_settings = {
  :address              => "smtp.gmail.com",
  :port                 => 587,
  :domain               => "my1040academy.com",
  :authentication       => "plain",
  :enable_starttls_auto => true,
  :user_name            => 'my1040academy',
  :password             => ENV["EMAIL_PASSWORD"] }